# Generated by Django 3.1.6 on 2021-02-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.CharField(max_length=10)),
                ('logout_time', models.CharField(max_length=10)),
                ('break_hours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.breakhours')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.days')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
        migrations.AddField(
            model_name='breakhours',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.days'),
        ),
    ]
